# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

[[main]]
  name = "Inicio"
  url = "/"
  weight = 10

[[main]]
  name = "Libro Blanco"
  url = "lib"
  weight = 20

[[main]]
  name = "Preámbulo"
  url = "lib"
  weight = 21
  parent = "Libro Blanco"

[[main]]
  name = "Sanidad sociosanitaria"
  url = "lib/sanidad"
  weight = 22
  parent = "Libro Blanco"
[[main]]
  name = "Medidas no faramcológicas"
  url = "lib/medidas-no-farmacologicas"
  weight = 23
  parent = "Libro Blanco"
[[main]]
  name = "Vacunas y planes de vacunación"
  url = "lib/vacunas"
  weight = 24
  parent = "Libro Blanco"
[[main]]
  name = "Salud mental"
  url = "lib/salud-mental"
  weight = 25
  parent = "Libro Blanco"
[[main]]
  name = "Hábitos saludables"
  url = "lib/habitos-saludables"
  weight = 26
  parent = "Libro Blanco"
[[main]]
  name = "Integración de la I+D+i"
  url = "lib/investigacion"
  weight = 27
  parent = "Libro Blanco"
[[main]]
  name = "Factores socioeconómicos"
  url = "lib/socioeconomia"
  weight = 28
  parent = "Libro Blanco"
[[main]]
  name = "Micro y mesoeconomía"
  url = "lib/micro-mesoeconomia"
  weight = 29
  parent = "Libro Blanco"
[[main]]
  name = "Política de comunicación"
  url = "lib/comunicacion"
  weight = 30
  parent = "Libro Blanco"
[[main]]
  name = "Gestión de datos abiertos"
  url = "lib/datos-abiertos"
  weight = 31
  parent = "Libro Blanco"
[[main]]
  name = "Marco legal"
  url = "lib/legal"
  weight = 32
  parent = "Libro Blanco"
[[main]]
  name = "Educación Infantil, Primaria y Secundaria"
  url = "lib/educacion-infantil-primaria-secundaria"
  weight = 33
  parent = "Libro Blanco"
[[main]]
  name = "Educación universitaria"
  url = "lib/educacion-universitaria"
  weight = 34
  parent = "Libro Blanco"

#[[main]]
#  name = "Noticias"
#  url = "post"
#  weight = 30

[[main]]
  name = "Equipo de trabajo"
  url = "people"
  weight = 40

[[main]]
  name = "Agenda"
#  url = "event"
  url = "#news"
  weight = 50

[[main]]
  name = "Recursos"
  url = "recursos"
  weight = 55

[[main]]
  name = "Contacto"
  url = "#contact"
  weight = 60