# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

[[main]]
  name = "Home"
#  url = "/"
  url = "portada-tmp"
  weight = 10

[[main]]
  name = "Libro Blanco"
  url = "lib"
  weight = 20

#[[main]]
#  name = "Noticias"
#  url = "post"
#  weight = 30

[[main]]
  name = "Equipo de trabajo"
  url = "people"
  weight = 40

[[main]]
  name = "Agenda"
  url = "event"
  weight = 50

[[main]]
  name = "Contacto"
  url = "contact"
  weight = 60
